---
- name: Check if rsyslog service exists
  hosts: all
  gather_facts: true
  tasks:

    - name: Check if rsyslog service is installed
      command: which rsyslogd
      register: rsyslog_status
      ignore_errors: yes

    - name: Print result for hosts with rsyslog
      debug:
        msg: "{{ ansible_facts['hostname'] }} {{ ansible_facts['distribution'] }}:{{ ansible_facts['distribution_major_version']}}"
      when: rsyslog_status.rc == 0

    - name: Print result for hosts without rsyslog
      debug:
        msg: "{{ inventory_hostname }}: rsyslog service does not exist"
      when: rsyslog_status.rc != 0

    - name: Print random to test
      debug:
        msg: "Random Message"
      when: rsyslog_status.rc == 0
